minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - lefthook
  - prisma
  - sharp
  - unrs-resolver

scriptsPrependNodePath: true
minimumReleaseAgeExclude:
  # Renovate security update: next@16.1.5
  - next@16.1.5
